updates for consistency
Signed-off-by: Alvin Ihsani <aihsani@nvidia.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -39,33 +39,29 @@ jobs:
         run: |
           root_dir=$PWD
           echo "$root_dir"
-
-          # build tar.gz and wheel
-          python setup.py check -m -s
-          python setup.py sdist bdist_wheel
-          python -m twine check dist/*
+          set -e
 
           # move packages to a temp dir
+          python setup.py sdist bdist_wheel --build-number $(date +'%Y%m%d%H%M')
           tmp_dir=$(mktemp -d)
           cp dist/monailabel* "$tmp_dir"
           rm -r build monailabel.egg-info
-          pushd "$tmp_dir"
+          cd "$tmp_dir"
           ls -al
 
+          # install from tar.gz
+          python -m pip install monailabel*.tar.gz
+          python -c 'import monailabel; monailabel.print_config()' 2>&1 | grep -iv "unknown"
+          python -c 'import monailabel; print(monailabel.__file__)'
+          python -m pip uninstall -y monailabel
+          rm monailabel*.tar.gz
+          
           # install from wheel
           python -m pip install monailabel*.whl
           python -c 'import monailabel; monailabel.print_config()' 2>&1 | grep -iv "unknown"
           python -c 'import monailabel; print(monailabel.__file__)'
           python -m pip uninstall -y monailabel
           rm monailabel*.whl
-
-          # install from tar.gz
-          name=$(ls *.tar.gz | head -n1)
-          echo $name
-          python -m pip install $name
-          python -c 'import monailabel; monailabel.print_config()' 2>&1 | grep -iv "unknown"
-          python -c 'import monailabel; print(monailabel.__file__)'
-          popd
 
           # install test utilities
           python -m pip install pytest
@@ -74,6 +70,11 @@ jobs:
           # and run the integration tests
           $root_dir/runtests.sh --net
 
+          # cleanup
+          cd "$root_dir"
+          rm -r "$tmp_dir"
+          rm -rf monailabel/
+          ls -la .
         env:
           shell: bash
 
@@ -89,7 +90,7 @@ jobs:
         run: |
           ls -al dist/
           rm dist/monai*.tar.gz
-          ls -al ../dist/
+          ls -al dist/
 
       - if: matrix.python-version == '3.8' #&& startsWith(github.ref, 'refs/tags/')
         name: Publish to Test PyPI
