Release workflow fixes (#148)
Updates to functioning release workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -36,21 +36,26 @@ jobs:
           python -m pip install torch>=1.5 torchvision
       - name: Build and test source archive and wheel file
         run: |
+          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
           root_dir=$PWD
           echo "$root_dir"
-
-          # build tar.gz and wheel
-          python setup.py check -m -s
-          python setup.py sdist bdist_wheel
-          python -m twine check dist/*
+          set -e
 
           # move packages to a temp dir
+          python setup.py sdist bdist_wheel --build-number $(date +'%Y%m%d%H%M')
           tmp_dir=$(mktemp -d)
           cp dist/monailabel* "$tmp_dir"
-          rm -r build dist monailabel.egg-info
+          rm -r build monailabel.egg-info
           cd "$tmp_dir"
           ls -al
 
+          # install from tar.gz
+          python -m pip install monailabel*.tar.gz
+          python -c 'import monailabel; monailabel.print_config()' 2>&1 | grep -iv "unknown"
+          python -c 'import monailabel; print(monailabel.__file__)'
+          python -m pip uninstall -y monailabel
+          rm monailabel*.tar.gz
+          
           # install from wheel
           python -m pip install monailabel*.whl
           python -c 'import monailabel; monailabel.print_config()' 2>&1 | grep -iv "unknown"
@@ -58,19 +63,18 @@ jobs:
           python -m pip uninstall -y monailabel
           rm monailabel*.whl
 
-          # install from tar.gz
-          name=$(ls *.tar.gz | head -n1)
-          echo $name
-          python -m pip install $name
-          python -c 'import monailabel; monailabel.print_config()' 2>&1 | grep -iv "unknown"
-          python -c 'import monailabel; print(monailabel.__file__)'
-
           # install test utilities
           python -m pip install pytest
 
           # start the monailabel server in the background
           # and run the integration tests
           $root_dir/runtests.sh --net
+
+          # cleanup
+          cd "$root_dir"
+          rm -r "$tmp_dir"
+          rm -rf monailabel/
+          ls -la .
         env:
           shell: bash
 
