Cleanup github workflows
Signed-off-by: Sachidanand Alle <sachidanand.alle@gmail.com>

diff --git a/.github/workflows/weekly-preview.yml b/.github/workflows/weekly-preview.yml
--- a/.github/workflows/weekly-preview.yml
+++ b/.github/workflows/weekly-preview.yml
@@ -2,7 +2,7 @@ name: weekly-preview
 
 on:
   schedule:
-  - cron: "0 2 * * 0"  # 02:00 of every Sunday
+    - cron: "0 2 * * 0"  # 02:00 of every Sunday
   workflow_dispatch:
 
 jobs:
@@ -12,51 +12,70 @@ jobs:
     env:
       DEV_RELEASE_VERSION: 0.3
     steps:
-    - uses: actions/checkout@v2
-      with:
-        ref: main
-        fetch-depth: 0
-    - name: Set up Python 3.8
-      uses: actions/setup-python@v2
-      with:
-        python-version:  3.8
-    - name: Install setuptools
-      run: |
-        python -m pip install --user --upgrade setuptools wheel
-    - name: Generate HEAD Commit Id
-      run: |
-        export HEAD_COMMIT_ID=$(git rev-parse HEAD)
-    - name: Build OHIF
-      run: |
-        root_dir=$(pwd)
-        ohif_dir=${root_dir}/plugins/ohif
-        pushd $ohif_dir
-        ./build.sh
-        popd
-    - name: Build distribution
-      run: |
-        export BUILD_OHIF=false
-        sed -i 's/name\ =\ monailabel$/name\ =\ monailabel-weekly/g' setup.cfg
-        echo "__commit_id__ = \"$HEAD_COMMIT_ID\"" >> monailabel/__init__.py
+      - uses: actions/checkout@v2
+        with:
+          ref: main
+          fetch-depth: 0
+      - name: Set up Python 3.8
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.8
+      - name: Install setuptools
+        run: |
+          python -m pip install --user --upgrade setuptools wheel
+      - name: Generate HEAD Commit Id
+        run: |
+          export HEAD_COMMIT_ID=$(git rev-parse HEAD)
+      - name: Build distribution
+        run: |
+          sed -i 's/name\ =\ monailabel$/name\ =\ monailabel-weekly/g' setup.cfg
+          echo "__commit_id__ = \"$HEAD_COMMIT_ID\"" >> monailabel/__init__.py
 
-        git config --global user.name "CI Builder"
-        git config --global user.email "monai.contact@gmail.com"
-        git diff setup.cfg monailabel/__init__.py
-        git add setup.cfg monailabel/__init__.py
-        git commit -m "Weekly build at $HEAD_COMMIT_ID"
+          git config --global user.name "CI Builder"
+          git config --global user.email "monai.contact@gmail.com"
+          git diff setup.cfg monailabel/__init__.py
+          git add setup.cfg monailabel/__init__.py
+          git commit -m "Weekly build at $HEAD_COMMIT_ID"
 
-        export YEAR_WEEK=$(date +'%y%U')
-        echo "Year week for tag is ${YEAR_WEEK}"
-        if ! [[ $YEAR_WEEK =~ ^[0-9]{4}$ ]] ; then echo "Wrong 'year week' format.  Should be 4 digits."; exit 1 ; fi
-        git tag "$DEV_RELEASE_VERSION.dev${YEAR_WEEK}"
-        git log -1
-        git tag --list
-        git describe --tags --dirty --always --long
-        python setup.py sdist bdist_wheel
-        git status
-        git ls-files -m
-    - name: Publish to PyPI
-      uses: pypa/gh-action-pypi-publish@master
-      with:
-        user: __token__
-        password: ${{ secrets.PYPI_TOKEN }}
+          export YEAR_WEEK=$(date +'%y%U')
+          echo "Year week for tag is ${YEAR_WEEK}"
+          if ! [[ $YEAR_WEEK =~ ^[0-9]{4}$ ]] ; then echo "Wrong 'year week' format.  Should be 4 digits."; exit 1 ; fi
+          git tag "$DEV_RELEASE_VERSION.dev${YEAR_WEEK}"
+          git log -1
+          git tag --list
+          git describe --tags --dirty --always --long
+
+          python setup.py sdist bdist_wheel
+      - name: Verify Package
+        run: |
+          tmp_dir=$(mktemp -d)
+          cp dist/monailabel* "$tmp_dir"
+          rm -r build monailabel.egg-info
+
+          # install from tar.gz
+          python -m pip install "$tmp_dir"/monailabel*.tar.gz
+          python -c 'import monailabel; monailabel.print_config()' 2>&1 | grep -iv "unknown"
+          python -c 'import monailabel; print(monailabel.__file__)'
+          python -m pip uninstall -y monailabel
+
+          # install from wheel
+          python -m pip install "$tmp_dir"/monailabel*.whl
+          python -c 'import monailabel; monailabel.print_config()' 2>&1 | grep -iv "unknown"
+          python -c 'import monailabel; print(monailabel.__file__)'
+          python -m pip uninstall -y monailabel
+
+          # install test utilities
+          python -m pip install pytest
+
+          # start the monailabel server in the background and run the integration tests
+          ./runtests.sh --net
+
+          # cleanup
+          rm -r "$tmp_dir"
+        env:
+          shell: bash
+      - name: Publish to PyPI
+        uses: pypa/gh-action-pypi-publish@master
+        with:
+          user: __token__
+          password: ${{ secrets.PYPI_TOKEN }}
